CREATE TABLE tb_gbooks_aggregated AS (
SELECT ANO_PUBLICACAO, CATEGORIA, DISPONIVEL_VENDA, DISPONIVEL_EPUB, DISPONIVEL_PDF,
SUM(NUMERO_PAGINAS) AS SOMA_NUMERO_PAGINAS, AVG(NUMERO_PAGINAS) AS MEDIA_NUMERO_PAGINAS,
SUM(PRECO) AS SOMA_PRECO, AVG(PRECO) AS MEDIA_PRECO 
FROM DB_GBOOKS.PUBLIC.TB_GBOOKS_CURATED TGC
GROUP BY ANO_PUBLICACAO, CATEGORIA, DISPONIVEL_VENDA, DISPONIVEL_EPUB, DISPONIVEL_PDF
);